/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/layout/BaseLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconCarbonTask: typeof import('~icons/carbon/task')['default']
    IconEpCalendar: typeof import('~icons/ep/calendar')['default']
    IconEpSearch: typeof import('~icons/ep/search')['default']
    IconEpSetting: typeof import('~icons/ep/setting')['default']
    IconFluentTaskListAdd20Filled: typeof import('~icons/fluent/task-list-add20-filled')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
